/**
 * Error Code Constants
 * Standardized error codes across the application
 */

export const ERROR_CODES = {
  // Text Generation
  TEXT_GENERATION_FAILED: "TEXT_GENERATION_FAILED",
  TEXT_GENERATION_ERROR: "GENERATION_ERROR",

  // Image Generation
  IMAGE_GENERATION_FAILED: "IMAGE_GENERATION_FAILED",

  // Video Generation
  VIDEO_GENERATION_FAILED: "VIDEO_GENERATION_FAILED",

  // Service Errors
  SERVICE_NOT_AVAILABLE: "SERVICE_NOT_AVAILABLE",
  SERVICE_NOT_FOUND: "SERVICE_NOT_FOUND",

  // Usage Errors
  USAGE_LIMIT_EXCEEDED: "USAGE_LIMIT_EXCEEDED",
  USAGE_LIMIT_WARNING: "USAGE_LIMIT_WARNING",

  // Validation Errors
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_INPUT: "INVALID_INPUT",

  // General Errors
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
};
